### ISSUE TITLE
The query to show inactive users is incorrect

### ISSUE THREAD

**Issue by paulsewardasc** [turbot/steampipe-plugin-snowflake#5]
**Describe the bug**
The query is using a ">" not a "<" which shows users logged in AFTER today - 30 days.

**To reproduce**
select
  name,
  email,
  disabled,
  last_success_login
from
  snowflake_user
where
  (last_success_login > now() - interval '30 days')
  and last_success_login is not null;

**Expected behavior**
This should be

select
  name,
  email,
  disabled,
  last_success_login
from
  snowflake_user
where
  (last_success_login < now() - interval '30 days')
  and last_success_login is not null;

**Comment by cbruno10** [comment]
Thanks for the report @paulsewardasc ! We'll take a look at this query example, and others across the other tables as well, and plan to release a new version later this week.

**Comment by cbruno10** [comment]
@paulsewardasc Sorry for the slight delay in fix this example query. The example will be updated on https://hub.steampipe.io/plugins/turbot/snowflake/tables/snowflake_user shortly once v0.1.1 is posted to the site.

Thanks again for the report!
