### ISSUE TITLE
Add table snowflake_resource_monitors

### ISSUE THREAD

**Issue by paulsewardasc** [turbot/steampipe-plugin-snowflake#7]
We us resource monitors to see how many credits have been used, I would like to graph this to show if the slope is changing or if we are near to out limit. "SHOW RESOURCE MONITORS" does this.
[table_snowflake_resource_monitor.txt](https://github.com/turbot/steampipe-plugin-snowflake/files/8632179/table_snowflake_resource_monitor.txt)

**Comment by cbruno10** [comment]
@paulsewardasc Thanks for raising this feature request!

I see you attached a file with some Go code inside, is this code you're currently using to query these resource types in a locally built plugin? I'm not familiar with that particular API or resource type yet, but I took a look at the code and it seemed to be directionally correct.

If it's something you're comfortable contributing, we'd really appreciate a new PR adding that table along with its doc with examples (which can be based off of how you use the table today). We'd be more than happy to provide feedback and review comments in that PR as well.

If this is something you're interested (or not) in contributing, please let us know!

**Comment by paulsewardasc** [comment]
Hi, I am using this code, it seems to work well. I will get some examples together and document. Not sure how to add a new PR though.

Paul

**Comment by paulsewardasc** [comment]
`select account as "Account",
    name as "Name", 
    credit_quota as "Credit Quota",
    used_credits as "Used Credits",
    remaining_credits as "Remaining Credits",
    to_char(used_credits/credit_quota*100,'9990D9') as "% Used",
    case
        when used_credits/credit_quota*100 > 90 then 'alert'
        when used_credits/credit_quota*100 > 75 then 'warning'
        else 'ok'
    end as type
from snowflake_resource_monitor
where used_credits/credit_quota*100 > 75
order by used_credits/credit_quota desc`
